# Generated by Django 2.2.3 on 2019-07-05 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('channel_id', models.CharField(db_index=True, max_length=50)),
                ('channel_access_token', models.TextField()),
                ('channel_secret', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('is_verify_webhook', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LineAccountTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0, help_text='For sorting')),
            ],
        ),
        migrations.CreateModel(
            name='LineContactTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tag', models.ManyToManyField(blank=True, related_name='groups', to='linemessageapi.LineAccountTag')),
            ],
        ),
        migrations.CreateModel(
            name='LineContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(db_index=True, max_length=50)),
                ('contact_type', models.CharField(choices=[('user', 'User'), ('group', 'Group'), ('room', 'Room')], max_length=16)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='linemessageapi.LineAccounts')),
                ('tag', models.ManyToManyField(blank=True, related_name='line_contacts', to='linemessageapi.LineContactTag')),
            ],
        ),
        migrations.AddField(
            model_name='lineaccounts',
            name='line_account_tag',
            field=models.ManyToManyField(blank=True, related_name='line_accounts', to='linemessageapi.LineAccountTag'),
        ),
    ]
