# Generated by Django 2.2.3 on 2019-07-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='status_cover',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
