# Generated by Django 2.2.3 on 2019-07-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_chatsession_status_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='status_cover',
            new_name='status_coversation',
        ),
    ]
