# Generated by Django 2.2.3 on 2019-07-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_auto_20190705_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='status_coversation',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status_coversation',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
