# Generated by Django 2.2.3 on 2019-07-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_auto_20190705_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatroom.ChatSession'),
        ),
    ]
